[book]
title = "Kubernetes CSI Developer Documentation"
description = "This site documents how to develop and deploy a Container Storage Interface (CSI) driver on Kubernetes."
authors = ["The Kubernetes Authors"]

[output.html]
additional-js = ["custom.js"]

[build]
build-dir = "../docs"
